compile:
  # Choosing to run compilation tests on 2 different Arduino platforms
  platforms:
    # - uno
    # - leonardo
    # - due
    # - zero
    # - m4
    - esp32
    # - esp8266
    # - mega2560
